# Generated by Django 3.0.6 on 2021-08-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_sendmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='body',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sendmail',
            name='html_data',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
