# Generated by Django 3.0.6 on 2021-08-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20210810_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailuser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mailuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sendmail',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MailUser',
        ),
        migrations.DeleteModel(
            name='SendMail',
        ),
    ]
